export const PATH = {
    CREATE_USER: "/cms/users/create",
    CATEGORIES: "/cms/categories",
    EDIT_CATEGORY: "/cms/categories/edit",
    NEW_CATEGORY: "/cms/categories/new",
    ORDERS_NEW: "/cms/orders/new",
    ORDERS_ALL: "/cms/orders",
    USERS: "/cms/users",
    PRODUCTS: "/cms/products/list",
    NEW_PRODUCT: "/cms/products/new",
    EDIT_PRODUCT: "/cms/products/edit",
    SITE_CONFIG: "/cms/config/site",
    LOGIN: "/",
    PROFILE: "/cms/profile",
    DASHBOARD: "/cms/dashboard",
    PAYMENT_METHODS: "/cms/payments/methods",
    BANNERS: "/cms/banners",
    UPLOAD_FILES: "/cms/upload/files",
    BRANDS: "/cms/brands",
    CREATE_BRAND: "/cms/brands/create"
}