import type { Metadata } from "next";
import AdminSideBar from "../components/AdminSideBar";
import AdminHeader from "../components/AdminHeader";
import AdminContent from "../components/AdminContent";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className='flex h-screen'>
            <AdminSideBar />
            <div className='flex flex-col flex-1 w-full'>
                <AdminHeader />
                <AdminContent>
                    {children}
                </AdminContent>
            </div>
        </div>
    );
}