import type { Metadata } from "next";
import AdminSideBar from "../components/AdminSideBar";
import AdminHeader from "../components/AdminHeader";
import AdminContent from "../components/AdminContent";
import { auth } from "../configs/auth.config";
import NextAuthSessionProvider from "../components/NextAuthSessionProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {

    const session = await auth()
    return (
        <div className='flex h-screen'>
            <AdminSideBar />
            <div className='flex flex-col flex-1 w-full'>
                <AdminHeader session={session} />
                <NextAuthSessionProvider session={session}>
                    <AdminContent>
                        {children}
                    </AdminContent>
                </NextAuthSessionProvider>
            </div>
        </div>
    );
}

export default RootLayout