interface Product {
    name?: string,
    description?: string,
    price?: number,
    stock?: number,
    category?: string,
    images?: string[],
    productCode?: string,
    options?: Variant[],
    // extras
    _id?: string,
    sold?: number,
    seller?: string,
    totalRatings?: number,
    averageRating?: number,
    remainingStock?: number,
    // ratings?: []
    brand?: string,
    createdAt?: string,
    updatedAt?: string,
    childrenCategories?: string[],
    packaging?: string,
    weight?: number,
    length?: number,
    width?: number,
    height?: number,
    information?: string,
    specifications?: string,
    ingredients?: string,
    usage?: string,
}